l_english:
  newsfeed_subject_label: "[Localize(Concatenate(Concatenate('newsfeed_subject_', SCOPE.GetFlagName('newsfeed_subject')), '_label'))|l]"
  newsfeed_type_label: "[Localize(Concatenate(Concatenate('newsfeed_type_', SCOPE.GetFlagName('newsfeed_type')), '_label'))|l]"

  newsfeed_subject_self_label: "Me"
  newsfeed_subject_spouse_label: "My [spouse|E]"
  newsfeed_subject_close_dynastic_family_label: "[close_family|E] of my [dynasty|E]"
  newsfeed_subject_extended_dynastic_family_label: "[extended_family|E] of my [dynasty|E]"
  newsfeed_subject_dynasty_label: "All characters of my [dynasty|E]"
  newsfeed_subject_liege_label: "My [liege|E]"
  newsfeed_subject_direct_vassal_label: "My direct [vassals|E]"
  newsfeed_subject_courtier_label: "My [courtiers|E]"
  newsfeed_subject_pinned_character_label: "My pinned characters"

  newsfeed_type_marriage_label: "[marriages|E]"
  newsfeed_type_pregnancy_label: "Pregnancies"
  newsfeed_type_birth_label: "Births"
  newsfeed_type_death_label: "[Concept('character_death', 'Deaths')|E]"
  newsfeed_type_offensive_war_label: "Offensive [wars|E]"
  newsfeed_type_defensive_war_label: "Defensive [wars|E]"
  newsfeed_type_titles_label: "[titles|E]"
  newsfeed_type_faith_label: "[faith|E]"
  newsfeed_type_culture_label: "[culture|E]"
